name: Main
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FORCE_COLOR: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Build and Test
        run: |
          cd tests
          cmake .
          cmake --build .
          ./StatsigClientSDKTests
